import os
from os import path
# В основном используется в апи dugacp, может ещё где нибудь :)

font = "./DUGAFONT.ttf"

# =================ПУТИ====================
paths = {
    "logo_cutout": os.path.join('graphics', 'logo_cutout.png'),
    "stone_wall": os.path.join('graphics', 'tiles', 'walls', 'stone_wall.png'),
    "stone_wall_crack": os.path.join('graphics', 'tiles', 'walls', 'stone_wall_crack.png'),
    "stone_vent": os.path.join('graphics', 'tiles', 'walls', 'stone_vent.png'),
    "stone_vase": os.path.join('graphics', 'tiles', 'walls', 'stone_vase.png'),
    "stone_end": os.path.join('graphics', 'tiles', 'walls', 'stone_end.png'),
    "baroque": os.path.join('graphics', 'tiles', 'walls', 'baroque.png'),
    "baroque_worn": os.path.join('graphics', 'tiles', 'walls', 'baroque_worn.png'),
    "baroque_lamps": os.path.join('graphics', 'tiles', 'walls', 'baroque_lamps.png'),
    "wood_wall": os.path.join('graphics', 'tiles', 'walls', 'wood_wall.png'),
    "wood_painting": os.path.join('graphics', 'tiles', 'walls', 'wood_painting.png'),
    "wood_books": os.path.join('graphics', 'tiles', 'walls', 'wood_books.png'),
    "wood_fireplace": os.path.join('graphics', 'tiles', 'walls', 'wood_fireplace.png'),
    "wood_end": os.path.join('graphics', 'tiles', 'walls', 'wood_end.png'),
    "wood_door": os.path.join('graphics', 'tiles', 'walls', 'wood_door.png'),
    "null": os.path.join('graphics', 'tiles', 'null.png'),
    "pillar": os.path.join('graphics', 'tiles', 'sprites', 'pillar.png'),
    "table": os.path.join('graphics', 'tiles', 'sprites', 'table.png'),
    "lysekrone": os.path.join('graphics', 'tiles', 'sprites', 'lysekrone.png'),
    "lysestage": os.path.join('graphics', 'tiles', 'sprites', 'lysestage.png'),
    "barrel": os.path.join('graphics', 'tiles', 'sprites', 'barrel.png'),
    "stone_pillar": os.path.join('graphics', 'tiles', 'sprites', 'stone_pillar.png'),
    "fern": os.path.join('graphics', 'tiles', 'sprites', 'fern.png'),
    "baroque_end": os.path.join('graphics', 'tiles', 'walls', 'baroque_door.png'),
    "baroque_door": os.path.join('graphics', 'tiles', 'walls', 'baroque_end.png'),
    "settings": os.path.join("data", "settings.dat"),
    "ak_spritesheet": os.path.join('graphics', 'weapon', 'ak_spritesheet.png'),
    "akitem": os.path.join('graphics', 'items', 'akitem.png'),
    "shotgun_spritesheet": path.join('graphics', 'weapon', 'shotgun_spritesheet.png'),
    "shotgun": path.join('graphics', 'items', 'shotgun.png'),
    "pistol_spritesheet": path.join('graphics', 'weapon', 'pistol_spritesheet.png'),
    "gun": path.join('graphics', 'items', 'gun.png'),
    "knife_spritesheet": path.join('graphics', 'weapon', 'knife_spritesheet.png'),
    "knifeitem": path.join('graphics', 'items', 'knifeitem.png'),
    "brass_spritesheet": path.join('graphics', 'weapon', 'brass_spritesheet.png'),
    "brassitem": path.join('graphics', 'items', 'brassitem.png'),
    "gauss_spritesheet": path.join('graphics', 'weapon', 'gauss_spritesheet.png'),
    "gaussitem": path.join('graphics', 'items', 'gaussitem.png'),
    "sgp_spritesheet": path.join('graphics', 'weapon', 'sgp_spritesheet.png'),
    "shotpistol": path.join('graphics', 'items', 'shotpistol.png'),
    "brass_brass_spritesheet": path.join('graphics', 'weapon', 'brass_brass_spritesheet.png'),
    "brassbrassitem": path.join('graphics', 'items', 'brassbrassitem.png'),
    "blood_brass_spritesheet": path.join('graphics', 'weapon', 'blood_brass_spritesheet.png'),
    "bloodbrassitem": path.join('graphics', 'items', 'bloodbrassitem.png'),
    "shiny_knife_spritesheet": path.join('graphics', 'weapon', 'shiny_knife_spritesheet.png'),
    "shinyknifeitem": path.join('graphics', 'items', 'shinyknifeitem.png'),
    "desert_knife_spritesheet": path.join('graphics', 'weapon', 'desert_knife_spritesheet.png'),
    "desertknifeitem": path.join('graphics', 'items', 'desertknifeitem.png'),
    "modded_shotgun_spritesheet": path.join('graphics', 'weapon', 'modded_shotgun_spritesheet.png'),
    "moddedshotgun": path.join('graphics', 'items', 'moddedshotgun.png'),
    "ak74_spritesheet": path.join('graphics', 'weapon', 'ak74_spritesheet.png'),
    "ak74item": path.join('graphics', 'items', 'ak74item.png'),
    "akext_spritesheet": path.join('graphics', 'weapon', 'akext_spritesheet.png'),
    "akextitem": path.join('graphics', 'items', 'akextitem.png'),
    "camo_ak_spritesheet": path.join('graphics', 'weapon', 'camo_ak_spritesheet.png'),
    "camoakitem": path.join('graphics', 'items', 'camoakitem.png'),
    "lightakitem": path.join('graphics', 'items', 'lightakitem.png'),
    "gauss_pistol_spritesheet": path.join('graphics', 'weapon', 'gauss_pistol_spritesheet.png'),
    "gaussgun": path.join('graphics', 'items', 'gaussgun.png'),
    "hpgun": path.join('graphics', 'items', 'hpgun.png'),
    "hpgun_spritesheet": path.join('graphics', 'weapon', 'pistol_spritesheet.png'),
    "lightak_spritesheet": os.path.join('graphics', 'weapon', 'ak_spritesheet.png'),
    "modded_gauss_spritesheet": path.join('graphics', 'weapon', 'modded_gauss_spritesheet.png'),
    "moddedgaussitem": path.join('graphics', 'items', 'moddedgaussitem.png'),
    "bump_gauss_spritesheet": path.join('graphics', 'weapon', 'bump_gauss_spritesheet.png'),
    "bumpgaussitem": path.join('graphics', 'items', 'bumpgaussitem.png'),
    "black_sgp_spritesheet": path.join('graphics', 'weapon', 'black_sgp_spritesheet.png'),
    "blackshotpistol": path.join('graphics', 'items', 'blackshotpistol.png'),
    "wtf_sgp_spritesheet": path.join('graphics', 'weapon', 'wtf_sgp_spritesheet.png'),
    "wtfshotpistol": path.join('graphics', 'items', 'wtfshotpistol.png'),
    "auto_pistol_spritesheet": path.join('graphics', 'weapon', 'auto_pistol_spritesheet.png'),
    "autogun": path.join('graphics', 'items', 'autogun.png')
}

spawn_mapping = {
    "ak47": 13,
    "shotgun": 10,
    "pistol": 16,
    "knife": 15,
    "brassknuckles": 11,
    "gauss": 7,
    "shotgunpistol": 14,
    "lightbrassknuckles": 8,
    "bloodybrassknuckles": 1,
    "sharpknife": 8,
    "lightknife": 10,
    "modifiedshotgun": 6,
    "tbshotgun": 6,
    "ak74": 8,
    "extmagak47": 10,
    "camoak47": 12,
    "lightak": 12,
    "anomalypistol": 1,
    "hppistol": 8,  # should be 16
    "moddedgauss": 4,
    "bumpgauss": 3,
    "moddedsgp": 6,  # should be 11 Black SGP
    "wtfsgp": 2,  # should be 3
    "autopistol": 8



}
